{% set version = '0.2019.0.1' %}
{% set buildnumber = 1 %}

package:
    name: daal4py
    version: {{version}}

source:
    path: ..
    #git_url: https://github.com/IntelPython/daal4py.git

requirements:
    build:
        - python
        - setuptools
        - numpy >=1.13
        - tbb-devel
        - daal-devel >=2019.0.0
        - daal-static >=2019.0.0   # [win]
        - cython
        - jinja2
        #- cnc >=1.2.300
    run:
        - python
        - numpy >=1.13
        - tbb
        - daal >=2019.0.0
        #- cnc >=1.2.300

build:
    number: {{buildnumber}}
    include_recipe: False

test:
    imports:
        - daal4py
    source_files:
        - examples/run_examples.py
        - examples/*batch.py
        - examples/data/batch
        #- examples/*spmd.py
        #- examples/*dspv.py
        #- examples/data/distributed
    commands:
        - cd examples && python run_examples.py

about:
    license: Apache 2.0
    license_file: LICENSE
