{% set version = '0.2019.1' %}
{% set buildnumber = 1 %}

package:
    name: daal4py
    version: {{version}}

source:
    path: ..
    #git_url: https://github.com/IntelPython/daal4py.git

requirements:
    build:
        - python
        - setuptools
        - numpy >=1.13
        - tbb-devel
        - daal-devel >=2019.0.0
        - daal-static >=2019.0.0   # [win]
        - cython
        - jinja2
    run:
        - python
        - numpy >=1.13
        - tbb
        - daal >=2019.0.0

build:
    number: {{buildnumber}}
    include_recipe: False

test:
    imports:
        - daal4py
    source_files:
        - examples/*batch.py
        - examples/data/batch
        - tests
    commands:
        - cd tests && python test_examples.py

about:
    license: Apache 2.0
    license_file: LICENSE
