{% set version = '0.2019.2' %}
{% set buildnumber = 0 %}

package:
    name: daal4py
    version: {{version}}

source:
    path: ..
    #git_url: https://github.com/IntelPython/daal4py.git

requirements:
    build:
        - python
        - setuptools
        - numpy >=1.13
        - tbb-devel
        - daal-devel >=2019.0
#        - daal-static  # [win and daal < 2019.1]
        - cython
        - jinja2
        - mpich                  # [not win]
        - impi-devel             # [win]
    run:
        - python
        - numpy >=1.13
        - tbb
        - daal >=2019.0
        - mpich                  # [not win]
        - impi_rt                # [win]

build:
    number: {{buildnumber}}
    include_recipe: False

test:
    imports:
        - daal4py
    source_files:
        - examples
        - tests

about:
    license: Apache 2.0
    license_file: LICENSE
