{% set version = '0.2019.2' %}
{% set buildnumber = 0 %}

package:
    name: daal4py
    version: {{version}}

source:
    path: ..
    #git_url: https://github.com/IntelPython/daal4py.git

requirements:
    build:
        - python
        - setuptools
        - numpy >=1.13
        - tbb-devel
        - daal-devel >=2019.0
        - daal-static >=2019.0   # [win]
        - cython
        - jinja2
        - mpich                  # [not win]
        - impi-devel             # [win]
    run:
        - python
        - numpy >=1.13
        - tbb
        - daal >=2019.0
        - mpich                  # [not win]
        - impi_rt                # [win]

build:
    number: {{buildnumber}}
    include_recipe: False

test:
    imports:
        - daal4py
    source_files:
        - examples/run_examples.py
        - examples/*batch.py
        - examples/*spmd.py
        - examples/data
        - tests
    commands:
        - cd tests && python test_examples.py; cd ..
        - cd examples && python run_examples.py

about:
    license: Apache 2.0
    license_file: LICENSE
